In [1]:
import torch

In [12]:
x = torch.rand(10, 5, 5, 25)[..., 21:25]
x

tensor([[[[0.2196, 0.5289, 0.9963, 0.2848],
          [0.4431, 0.4702, 0.9432, 0.4848],
          [0.7243, 0.8680, 0.0015, 0.3388],
          [0.5706, 0.8519, 0.7587, 0.2971],
          [0.2569, 0.0859, 0.9506, 0.7298]],

         [[0.4483, 0.5023, 0.4660, 0.7794],
          [0.9291, 0.9654, 0.3047, 0.7974],
          [0.7439, 0.5726, 0.9870, 0.0997],
          [0.8933, 0.7930, 0.4507, 0.7423],
          [0.3852, 0.9249, 0.9698, 0.2024]],

         [[0.6656, 0.0955, 0.2049, 0.1109],
          [0.1624, 0.7056, 0.4351, 0.4646],
          [0.6433, 0.6057, 0.1983, 0.6641],
          [0.6392, 0.9600, 0.9050, 0.0507],
          [0.6929, 0.1867, 0.0319, 0.0910]],

         [[0.1998, 0.0929, 0.7638, 0.4079],
          [0.6911, 0.6452, 0.6870, 0.4105],
          [0.9735, 0.2644, 0.2200, 0.9654],
          [0.8996, 0.9689, 0.1564, 0.6275],
          [0.1457, 0.2966, 0.9139, 0.8564]],

         [[0.8346, 0.5133, 0.0481, 0.1511],
          [0.5866, 0.2683, 0.6575, 0.7416],
          [0.7453, 0.306

In [24]:
torch.sign(torch.tensor([-5, 2]))

tensor([-1,  1])

In [16]:
torch.sqrt(torch.sign(-x))

tensor([[[[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]],

         [[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]],

         [[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]],

         [[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]],

         [[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]]],


        [[[nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan],
          [nan, nan, nan, nan]],

         [[nan, nan, nan, 